### ISSUE TITLE
[PE-D][Tester B] Accepts Invalid Phone number for Editing 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-F13-1/tp#209] opened 2023-11-03 21:08 UTC
Accepts Invalid unreasonable phone number, which reduces data intgrity

![image.png](https://raw.githubusercontent.com/kimshitong/ped/main/files/c5ae37c5-4697-453e-93a1-1fe5bc41e3f8.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kimshitong/ped#10

**Comment by xavierpok** [comment] 2023-11-04 13:58
Essentially a duplicate of #201. Closing.

**Closed by xavierpok** 2023-11-04 13:58 UTC
